### ISSUE TITLE
Sending not working, problems with signing

### ISSUE THREAD

**Issue by rockstardev** [bscheiman/BlockCypher#2]
First of all - thanks for great library. I'm trying to use it to send BTC - but whenever I try your Send method I end up with HTTP error 400.

I haven't added anything to the code so you should be able to reproduce it by simply running the library - probably BlockCypher changes something on the backend.

Let me know if you are willing to help - if needed I can provide logs of HTTP calls and responses.

Thanks again!

**Comment by bscheiman** [comment]
Sure, please send logs. They will definitely help.

**Comment by rockstardev** [comment]
I've figured it out - it had to do with the fact that that `Confirmed` field was not initialized and when API receives JSON it fails saying this:

`{"error": "Couldn't deserialize request: parsing time ""0001-01-01T00:00:00"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00""}` 

You can see how I quick-fixed it here:
https://github.com/lepipele/BlockCypher/commit/ec01684b221bd0a93af59964b1d9b70fb060a7d6

Also, I've made improvements to NuGet restore so that csproj can be referenced and then path to `packages` folder will be resolved using $(SolutionDir). If you like the changes I can issue pull request and you can go from there.

**Comment by bscheiman** [comment]
Go for it, I'll merge

**Comment by rockstardev** [comment]
Thanks man - I've created pull request.

Also, looking at sending and the fact that fees are like 8 cents per transaction now - I'll start looking into Micro-transaction API: http://dev.blockcypher.com/#microtransaction-endpoint

I don't know if I'll manage to implement the call that requires signing or only the one with private key - but if I do, I'll do another pull. If you beat me to it - let me know ;) I'll monitor the repo.

Thanks again for your great work!
